### ISSUE TITLE
Incorrect spacing when first argument shifted

### ISSUE THREAD

**Issue by a1isaeed** [Gruntfuggly/shifter#3]
Shifting the **first argument** (or array item) results in incorrect spacing:

```js
// before
const items = ['apple', 'banana', 'cherry'];
function eat(appetizer, main, dessert) {
  // ...
}

// after
const items = [ 'banana','apple', 'cherry'];
function eat( main,appetizer, dessert) {
  // ...
}
```

I'm using **Shifter 0.0.5** on VSCode 1.44.2.

**Comment by Gruntfuggly** [comment]
Yes, unfortunately it's a known issue. The extension doesn't know how the list should be formatted, so it leaves the content between the commas as it was.
I could add an option to format the list after shifting, but I don't know if it will causes further issues...

**Comment by Gruntfuggly** [comment]
Latest version now formats the list after shifting.
