### ISSUE TITLE
Edge case not working properly

### ISSUE THREAD

**Issue by sfsr12** [Gruntfuggly/shifter#5]
I have an example that is not working correctly

```js
await fill(context, value, '//tr[contains(@class, "new")]//td[@class="value"]/form/input');
```

If you try to shift `value` or the xPath expression, they end up getting combined into one value.

Just thought I would report it.

**Comment by Gruntfuggly** [comment]
To be honest, it's a very simple extension - it doesn't parse the code in any way - it just searches for commas and brackets. There are lots of edge cases unfortunately.

**Comment by sfsr12** [comment]
Cool, no worries, didn’t know if it was something that would be surprising. 

Totally get the minimal nature of it, and it is super helpful in 99% of my cases even with one that have lots of xpath and regex in them. 

Thanks for making it!

**Comment by Gruntfuggly** [comment]
The problem in this case is that is doesn't know about strings containing commas, etc. which it should ignore. If you wanted to have a go at improving it, there are two functions in the code: `findForward` and `findBackward`. They currently don't take account of whether the current character is within a string or not - if it found a quote or double quote, it could skip forwards (or backwards) until it found a match. That would improve it and fix lots of cases, but you still run into the problem of escaped quotes.

Unfortunately, I don't have any spare time to do it myself currently.
