### ISSUE TITLE
Doesn't appear to work with array parameters

### ISSUE THREAD

**Issue by sol3uk** [Gruntfuggly/shifter#7]
![l7qoTMYH2Y](https://user-images.githubusercontent.com/26093813/136659394-a0c49723-fc5b-4f11-90ba-8a1fa22c2032.gif)

**Comment by Gruntfuggly** [comment]
I don't think It's clever enough to understand the nesting. There's no tokenisation - it's just tries to match brackets.

Could you post a snippet of your code as text so I can try it out?

**Comment by sol3uk** [comment]
Oh that's fine if it's not build around tokenisation I get it. I was looking for something that could shift the parameters for constructors and also reflect that in all instance calls of that class constructor or method but I guess no one has done it 😅

Just try with any array as a parameter, it'll swap it to be inside the brackets:
`let tester = new Item(test, ["array", "wow"]);`
